import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Toaster } from "~/components/ui/sonner";
import Nav from "~/components/Nav";
import Provider from "~/components/Provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
<html lang="en" className={`min-h-screen ${geist.variable}`}>
  <body className=" w-full">
    <Provider>
        <Toaster />
      <main className="w-full  min-h-screen border-4 bg-red-500">
        <Nav />
        <div className="w-full ">
          {children}
        </div>
      </main>
    </Provider>
  </body>
</html>
  );
}
