import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Toaster } from "~/components/ui/sonner";
import Nav from "~/components/Nav";
import Provider from "~/components/Provider";
import Footer from "~/components/Footer";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import Loader from "~/components/Loader";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`min-h-screen ${geist.variable}`}>
      <body className="relative w-full">
        <Provider>
         <Suspense fallback={<Loader/>}>
           <main className="relative z-20 min-h-screen w-full bg-zinc-200 px-10 backdrop-blur-2xl">
            <Nav />
            <div className="w-full">{children}</div>
          </main>

          <div className="relative z-0 h-screen w-full"></div>

          <Footer />
         </Suspense>
        </Provider>
      </body>
    </html>
  );
}
